export default [
    {
        "id": 1,
        "name": "Intro to Web Development",
        "description": "Learn how to create interactive and engaging web pages using HTML, CSS, and JavaScript",
        "enrolled": true,
        "progress": 50,
    },
    {
        "id": 2,
        "name": "Version Control with Git",
        "description": "Learn how to manage code, collaborate with others, and track changes in a project's codebase.",
        "enrolled": true,
        "progress": 82,
        "longDescription": "Version control is an essential tool for software development, collaboration, and project management. Git is a widely-used and powerful version control system that enables developers to track changes, manage versions, and collaborate with others efficiently. This course provides a comprehensive introduction to version control using Git. Students will learn how to install and configure Git, create repositories, track changes, and collaborate with others using Git. They will also learn best practices for using Git and how to resolve common issues that arise during the development process.   This course is designed for software developers, project managers, and anyone who wants to learn how to use Git for version control. It is suitable for both beginners and those with some experience with Git who want to improve their skills. By the end of the course, students will have a strong understanding of version control using Git, and they will be able to use Git to manage their projects more efficiently and collaboratively.",
       },
    {
        "id": 3,
        "name": "Linux Command",
        "description": "Learn to navigate the Linux terminal, manipulate files and directories, and perform basic system administration tasks using various commands and utilities.",
        "enrolled": true,
        "progress": 2,
    },
    {
        "id": 4,
        "name": "Python Programming",
        "description": "Learn about the key concepts and principles of Python, including data types, variables, operators, and control structures.",
        "enrolled": true,
        "progress": 35,
    },
    {
        "id": 5,
        "name": "Intro to Data Science With Python",
        "description": "Master the basics of data analysis, including data cleaning and preparation, exploratory data analysis, and statistical inference with Python.",
        "enrolled": false,
        "progress": 50,
    },
    {
        "id": 6,
        "name": "Networking Fundamentals",
        "description": "Learners will be introduced to the basics of computer networking, including network topologies, network protocols, and network devices.",
        "enrolled": false,
        "progress": 0,
    },
    {
        "id": 7,
        "name": "Cyber Security Fundamentals",
        "description": "Designed to provide learners with a comprehensive understanding of the fundamental concepts and techniques used in cyber security.",
        "enrolled": false,
        "progress": 0,
    },
    {
        "id": 8,
        "name": "Programming in C",
        "description": "Learners will be introduced to the basics of C programming, including data types, control structures, functions, and pointers.",
        "enrolled": false,
        "progress": 0,
    },

]